# Generated by Django 5.0.6 on 2024-06-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_duration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ("id",), "verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
    ]
